# fruits = list(input("Enter the fruits you like and seperate with commas: ").split(","))
# print(fruits)

fruits =[]
f1 = input("Enter the fruits you like: ")
fruits.append(f1)
f2= input("Enter the fruits you like: ")
fruits.append(f2)
f3 = input("Enter the fruits you like: ")
fruits.append(f3)
f4 = input("Enter the fruits you like: ")
fruits.append(f4)
f5 = input("Enter the fruits you like: ")
fruits.append(f5)
f6 = input("Enter the fruits you like: ")
fruits.append(f6)
f7 = input("Enter the fruits you like: ")
fruits.append(f7)
print(fruits)
